#define NUITKA_COMPANY_NAME "LaobingStudio"
#define NUITKA_PRODUCT_NAME "TeacherHelper"
#define NUITKA_VERSION_COMBINED "0.1.4.0"
#define _NUITKA_BUILD_DEFINITIONS_CATALOG "NUITKA_COMPANY_NAME,NUITKA_PRODUCT_NAME,NUITKA_VERSION_COMBINED,_NUITKA_ONEFILE_TEMP_SPEC,_NUITKA_ONEFILE_TEMP_BOOL,_NUITKA_ONEFILE_COMPRESSION_BOOL,_NUITKA_ONEFILE_BUILD_BOOL,_NUITKA_BUILD_DEFINITIONS_CATALOG"
#define _NUITKA_ONEFILE_BUILD_BOOL 1
#define _NUITKA_ONEFILE_COMPRESSION_BOOL 1
#define _NUITKA_ONEFILE_TEMP_BOOL 1
#define _NUITKA_ONEFILE_TEMP_SPEC "%TEMP%\\onefile_%PID%_%TIME%"
